name: Destroy
on:
  workflow_dispatch:

jobs:
  Destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Get Name of server and sg
        run: |
          echo "sgID=$(aws ec2 describe-instances --filters "Name=instance.group-name,Values=server_group" --query "Reservations[*].Instances[*].InstanceId" --output text)" >> $GITHUB_ENV
          echo "ec2ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=devops_portfolio" --query "Reservations[*].Instances[*].InstanceId" --output text)" >> $GITHUB_ENV

      - name: remove role
        run: |
          aws iam remove-role-from-instance-profile --instance-profile-name 'ssm_instance_profile' --role-name 'ssm_role'
          aws iam detach-role-policy --role-name 'ssm_role' --policy-arn 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
          aws iam delete-role --role-name 'ssm_role'

      - name: delete instance profile 
        run: aws iam delete-instance-profile --instance-profile-name 'ssm_instance_profile'

      - name: delete SG and instance
        run: |
          aws ec2 delete-security-group --group-id ${{ env.sgID }}
          aws ec2 terminate-instances --instance-ids ${{ env.ec2ID }}


      # TODO: Add route53 dns deletion step when tis added